name: Post-merge Summary

on:
  pull_request:
    types: [closed]
    branches: [main, dev]

jobs:
  summary:
    uses: prasadnayak-sudo/ci-workflows/.github/workflows/post-merge-summary.yml@v1
    secrets: inherit
